export const vaultProtocolConstants = Object.freeze({
  protocolVersion: 2,
  cryptoSuite: 'HKDF-SHA256/AES-256-GCM',
  aesAlgorithm: 'AES-GCM',
  hkdfAlgorithm: 'HKDF',
  sha256Algorithm: 'SHA-256',
  aesKeyLength: 256,
  vmkLength: 32,
  nonceLength: 12,
  maxPlaintextBytes: 5_000_000,
  maxCiphertextBytes: 5_000_016,
  maxSnapshotBytes: 6_000_000,
  domainSeparator: 'budgetflow/snapshot-signature/v2',
  localLabel: 'budgetflow/local-records/v2',
  syncLabel: 'budgetflow/sync-snapshot/v2',
  checkLabel: 'budgetflow/key-check/v2',
  deviceLabel: 'budgetflow/device-wrap/v1',
  passkeyLabel: 'budgetflow/passkey-wrap/v1',
  deviceWrapPurpose: 'device-wrap',
  passkeyWrapPurpose: 'passkey-wrap',
  vmkEnvelopeVersion: 1,
  maxShareLength: 32,
  sentinelValue: 'budgetflow-v2-key-confirmation',
  envelopeHeaderKeys: [
    'accountId',
    'collection',
    'cryptoSuite',
    'formatVersion',
    'keyId',
    'recordId',
    'vaultId',
    'workspaceId',
    'nonce',
  ],
  snapshotHeaderKeys: [
    'accountId',
    'createdAt',
    'createdByDeviceId',
    'cryptoSuite',
    'formatVersion',
    'keyId',
    'nonce',
    'previousEnvelopeHash',
    'revision',
    'vaultId',
    'workspaceId',
  ],
  wrapHeaderKeys: [
    'accountId',
    'credentialId',
    'cryptoSuite',
    'deviceId',
    'formatVersion',
    'keyId',
    'purpose',
    'vaultId',
    'workspaceId',
    'nonce',
  ],
});
