export const COMPANY_FORM_VARIANTS: readonly string[] = [
  'p.h.u',
  'p.h.u.',
  'phu',
  'f.h.u',
  'f.h.u.',
  'fhu',
  'p.p.h.u',
  'p.p.h.u.',
  'pphu',
  'sp. z o.o.',
  'sp. z o.o',
  'sp.z o.o.',
  'spółka z o.o.',
  'spółka z ograniczoną odpowiedzialnością',
  's.c.',
  'sp.j.',
  'sp. j.',
  'spółka jawna',
  'sp.k.',
  'sp. k.',
  'spółka komandytowa',
  's.a.',
  'spółka akcyjna',
  'z.p.h.u',
  'z.p.h.u.',
  'zakład',
  'przedsiębiorstwo',
];
