import { InviteCode } from '@invite-codes/domain/invite-code.entity';

export const INVITE_CODE_REPOSITORY = Symbol('INVITE_CODE_REPOSITORY');

/**
 * ARCH-EXCEPTION: global-scope — Invite codes are Superuser-only admin resources,
 * not workspace-scoped data. A code is generated by any Superuser and redeemed
 * globally during registration (before workspace exists).
 */
export interface InviteCodeRepository {
  save(code: InviteCode): Promise<InviteCode>;
  findById(id: string): Promise<InviteCode | undefined>;
  findByCode(code: string): Promise<InviteCode | undefined>;
  findAll(): Promise<ReadonlyArray<InviteCode>>;
  delete(id: string): Promise<void>;
}
